# Generated by Django 3.1.4 on 2020-12-22 00:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
