# Generated by Django 3.1.4 on 2020-12-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20201222_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='md5',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
    ]
