# Generated by Django 3.1.4 on 2020-12-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20201222_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
    ]
